### PR TITLE
support for std::string_view when using C++17

### PR DESCRIPTION
**Pull request by dermojo**
See issue #259

### CODE REVIEW

**Comment by dermojo** [comment]
VS2017 doesn't build, but the errors look unrelated to my changes...

**Comment by rbock** [comment]
Nice work.

Can you add a test?
Ideally, also adjust `.travis.yml`.

Thanks,

Roland

**Comment by dermojo** [comment]
Thanks.
I tested a few things and the easiest/best way to compile for C++17 is to allow to - optionally - specify a C++ standard in the CMakelists.txt. This can then be selected from the command line, e.g. when building with travis.
I think I will add this tomorrow.

**Comment by dermojo** [comment]
I adapted the CMakeLists.txt for all tests to allow building them with an arbitrary C++ standard.
This cannot be done for the sqlpp11 library itself (it's an INTERFACE target), but for all tests using it.

Also, travis now builds the release version twice: once like before and once with C++ 17.
Currently, the C++17 only do something different on OS X, because the clang and gcc versions on the Linux image are too old, so there's still some potential for optimization...

**Comment by rbock** [comment]
Nicely done! Thanks for the effort!

(sorry for the late answer, I was offline for a few days)

**Comment by dermojo** [comment]
Great, thanks a lot for a very interesting library!

**Pull request merged**
