### PR TITLE
Align CMake files with 4 spaces indent

### PR DESCRIPTION
**Pull request by hwhsu1231**
Align CMake files with 4 spaces indentation.

### CODE REVIEW

**Comment by rbock** [comment]
What is the rationale for the change?

**Comment by hwhsu1231** [comment]
To make the CMake codes more tidy since the previous indentation is a mixture of 4 spaces, 2 spaces, tabs.

**Comment by rbock** [comment]
I see, thanks for he explanation.

**Comment by rbock** [comment]
And thanks for cleaning this up :-)

**Comment by Leon0402** [comment]
> To make the CMake codes more tidy since the previous indentation is a mixture of 4 spaces, 2 spaces, tabs.

Do you use tooling for this? If yes, what tool are using?

**Comment by hwhsu1231** [comment]
Just manually adjust it myself.

**Pull request merged**
