### PR TITLE
Fixed compile error when include connection_pool.h using c++11

### PR DESCRIPTION
**Pull request by choiip**
Fixed syntax error and some line of code using c++14 features.

### CODE REVIEW

**Comment by rbock** [comment]
Thanks!

You seem to be using different indenting rules. Can you apply clang-format with the .clang-format rules in the repository?

Please be aware that the connection pool is a very early prototype.

**Comment by choiip** [comment]
Thanks for your advise. I will fix it soon.

**Comment by choiip** [comment]
I applied clang-format with the .clang-format rules in the repo. Any plan on merge the changes? Thanks.

**Comment by rbock** [comment]
Thanks :-)

**Pull request merged**
