### PR TITLE
Add vcpkg installation instructions

### PR DESCRIPTION
**Pull request by NancyLi1013**
`sqlpp11` is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for sqlpp11 and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build sqlpp11, ready to be included in their projects.

We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64, arm, uwp) to keep a wide coverage for users.

I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/sqlpp11/portfile.cmake). We try to keep the library maintained as close as possible to the original library.

### CODE REVIEW

**Comment by rbock** [comment]
Hi NancyLi1013,

Thanks for making sqlpp11 available via vcpkg and for the additional documentation!

How do you handle the connector libraries? Are they maintained as separate packages? Or will they come with sqlpp11?

Best,

Roland

**Comment by NancyLi1013** [comment]
Hi rbock,

Thanks for your review.

The connector libraries such as `sqlite3` and `mysql` are come with sqlpp11, which are named as `sqlpp11-connector-sqlite3` and `sqlpp11-connector-mysql`. 

Both of these two ports are maintained as separate packages in vcpkg now.

[sqlpp11-connector-sqlite3](https://github.com/microsoft/vcpkg/tree/master/ports/sqlpp11-connector-sqlite3)
[sqlpp11-connector-mysql](https://github.com/microsoft/vcpkg/tree/master/ports/sqlpp11-connector-mysql)
 
Thanks,
Nancy

**Comment by rbock** [comment]
Hi Nancy,

Thanks for the information. It might make sense to add this information to the readme, too. Or would this be obvious for vcpkg users?

Best,

Roland

**Comment by NancyLi1013** [comment]
Hi rbock,

`sqlpp11`, `sqlpp11-connector-sqlite3` and `sqlpp11-connector-mysql` are all listed in `ports` folder. The users can find these ports here in vcpkg. But there is no separate doc or description about this.

If possible, it might be better to add the information to `readme`. 

Thanks,
Nancy

**Comment by rbock** [comment]
Hi Nancy,

Please feel free to add another pull request.

Thanks,

Roland

**Pull request merged**
