### PR TITLE
The first working implementation

### PR DESCRIPTION
**Pull request by niXman**
The first working implementation.
Example added.(examples/ppgen.cpp)
But I can`t add the Boost detection to the CMakeLists.txt. I did the same as described here[1], but unsuccessfully. Can you please do it by yourself?

Ok to merge?

[1] https://stackoverflow.com/questions/6646405/how-do-you-add-boost-libraries-in-cmakelists-txt

### CODE REVIEW

**Comment by rbock** [comment]
I took a quick look at the code. From what I can gather, it looks quite clean and good. I'll try to merge and take care of the Boost detection within the next few days.

I'll let you know as soon as possible, of course.

**Comment by niXman** [comment]
Ok.

**Comment by rbock** [comment]
find_package(Boost)
if (Boost_FOUND)
	MESSAGE("Boost Found")
else()
	MESSAGE("Boost not found")
endif()

Seems to work fine. It does not check for the preprocessor, but it should be OK for now.

Need to sleep now :-)

**Comment by rbock** [comment]
Which version of boost do you use? I have 1.54 on my machine, and get this:

$ make
-- Using /usr/bin/c++ (compiler id: GNU)
-- Boost version: 1.54.0
/usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rbock/temp/nixman/sqlpp11
[ 16%] Built target UnionTest
[ 33%] Built target Sqlpp11Exampleinsert
[ 50%] Building CXX object examples/CMakeFiles/Sqlpp11Exampleppgen.dir/ppgen.cpp.o
In file included from /home/rbock/temp/nixman/sqlpp11/examples/ppgen.cpp:38:0:
/home/rbock/temp/nixman/sqlpp11/include/sqlpp11/ppgen.h:74:50: fatal error: boost/preprocessor/tuple/pop_front.hpp: No such file or directory
 #include <boost/preprocessor/tuple/pop_front.hpp>
                                                  ^
compilation terminated.
make[2]: *** [examples/CMakeFiles/Sqlpp11Exampleppgen.dir/ppgen.cpp.o] Error 1
make[1]: *** [examples/CMakeFiles/Sqlpp11Exampleppgen.dir/all] Error 2
make: *** [all] Error 2

$ ls /usr/include/boost/preprocessor/tuple
eat.hpp  elem.hpp  enum.hpp  rem.hpp  reverse.hpp  size.hpp  to_array.hpp  to_list.hpp  to_seq.hpp

pop_front.hpp is available in array of seq though.

**Comment by niXman** [comment]
> Which version of boost do you use?

1.57.
`BOOST_PP_TUPLE_POP_FRONT()` is available in 1.56 or greater.

**Comment by rbock** [comment]
I have very little knowledge of boost preprocessing. Would it be hard to make your code work with slightly older versions?

If yes, then we can stick with 1.56 and greater, of course.

**Comment by niXman** [comment]
I have to add the implementation of `BOOST_PP_TUPLE_POP_FRONT()` into `ppgen`...

**Comment by rbock** [comment]
OK, lets wait for feedback first. I'll install a more recent version on my machine.

**Comment by rbock** [comment]
OK, I have boost 1.57 now, works fine :-)
And the code in the example is really quite nice!

How did you produce the preprocessor output you showed me earlier? Is there something like boost_stringify for the generated table code?

**Comment by niXman** [comment]
> How did you produce the preprocessor output you showed me earlier?

Like this: `g++ -std=c++11 -E main.cpp > out.hpp && clang-format-3.5 -i out.hpp`

**Comment by niXman** [comment]
I have to try to add the implementation of `BOOST_PP_TUPLE_POP_FRONT()` into `ppgen`?

**Comment by rbock** [comment]
I think, for the time being, I'll write that boost-1.56 is required to use ppgen. I just merged and will add the boost-lookup to the CMakeLists tomorrow.

Thank you very much for implementing the preprocessor table generator!

**Comment by niXman** [comment]
> I think, for the time being, I'll write that boost-1.56 is required to use ppgen. I just merged and will add the boost-lookup to the CMakeLists tomorrow.

Ok.

> Thank you very much for implementing the preprocessor table generator!
My pleasure ;)

**Pull request merged**
