### PR TITLE
Sql2ddl tests

### PR DESCRIPTION
**Pull request by digitalist**
- cmake-time check for python / pyparsing
- ddl2cpp good and bad samples

@rbock  by the way, what's a canocial way to run automated tests for sqlpp11, I know it's a silly question, but

### CODE REVIEW

**Comment by digitalist** [comment]
oops, I see

**Comment by digitalist** [comment]
It seems python should be added to AppVeyor build

**Comment by digitalist** [comment]
I'm closing this PR, I'll try to debug travis  tests from the fork, so I don't annoy you with messages

**Comment by rbock** [comment]
Hi,

It is good to see the progress :-)

I am wondering if it might make sense to have one platform without python (on purpose) to verify that the tests are not run unless python is available? e.g. run the tests for debug builds but not for production?

Best,

Roland

**Comment by digitalist** [comment]
Script tests will not run unless cmake finds python, guess they covered it
for us.

**Comment by digitalist** [comment]
Ah, seems I see your point, I'll look into this

**Pull request closed without merging**
