### PR TITLE
Fix build on x86

### PR DESCRIPTION
**Pull request by fedddddd**
Also fixed a few warnings

### CODE REVIEW

**Comment by rbock** [comment]
Thanks for the PR. Can you share some errors/warnings that you are seeing?

**Comment by fedddddd** [comment]
Errors:
```
sqlpp11\include\sqlpp11\mysql\detail\connection_handle.h(75,16): error C2660: 'std::unique_ptr<MYSQL,void (__cdecl *)(MYSQL *)>::unique_ptr': function does not take 2 arguments	
```
Warnings:
```
sqlpp11\include\sqlpp11\mysql\connection.h(210,31): warning C4244: 'return': conversion from 'my_ulonglong' to 'size_t', possible loss of data
sqlpp11\include\sqlpp11\mysql\connection.h(216,35): warning C4244: 'return': conversion from 'my_ulonglong' to 'size_t', possible loss of data
sqlpp11\include\sqlpp11\mysql\connection.h(222,35): warning C4244: 'return': conversion from 'my_ulonglong' to 'size_t', possible loss of data
sqlpp11\include\sqlpp11\mysql\connection.h(240,36): warning C4244: 'return': conversion from 'my_ulonglong' to 'size_t', possible loss of data
sqlpp11\include\sqlpp11\mysql\connection.h(246,40): warning C4244: 'return': conversion from 'my_ulonglong' to 'size_t', possible loss of data
sqlpp11\include\sqlpp11\mysql\connection.h(252,40): warning C4244: 'return': conversion from 'my_ulonglong' to 'size_t', possible loss of data
```

**Comment by rbock** [comment]
Thanks, I admit I never noticed `STDCALL` before.
Why is that necessary?

**Comment by fedddddd** [comment]
Well because the `mysql_close` function, which is used in `connection_handle` (`std::unique_ptr<MYSQL, void (*)(MYSQL*)> mysql;`), is defined as stdcall

**Comment by rbock** [comment]
Ah, and on some systems that evaluates to nothing.

Seems reasonable, merged :-)

**Pull request merged**
