### PR TITLE
Fix blob result_type

### PR DESCRIPTION
**Pull request by blastrock**

### CODE REVIEW

**Comment by blastrock** [comment]
I added support for std::array, I hope I didn't miss anything ^^

So, do you think we could merge this feature to master? Or is there still work to do?

**Comment by rbock** [comment]
Nice work! Thanks :-)

Will merge into master, soon.

**Comment by rbock** [comment]
Merged to develop now. Can you check if it works OK? (Just to be sure, I had a few merge conflicts).

**Comment by blastrock** [comment]
develop works for me, with my branch on sqlpp11-connector-sqlite3

**Pull request merged**
