### PR TITLE
Add support for parameterized_verbatim

### PR DESCRIPTION
**Pull request by MacDue**
Adds a ``sqlpp11::parameterized_verbatim`` escape hatch for tricky or database specific prepared statements.

### CODE REVIEW

**Comment by MacDue** [comment]
This addresses #340

**Comment by rbock** [comment]
Hi, 

Thanks for the pull request! The changes look very good to me.

Any idea, why "Rebase and merge" detects a merge conflict?

Best,

Roland

**Comment by MacDue** [comment]
Not too sure. Maybe just squash merge this one? (GitHub seems to be telling me there are no conflicts)

**Comment by rbock** [comment]
Done. Thanks again :-)

**Pull request merged**
