### PR TITLE
First working implementation

### PR DESCRIPTION
**Pull request by niXman**
Hi,

Please review the first working implementation.

For this macro-function:
```cpp
SQLPP_DECLARE_TABLE(
	(table)
	,
	(id, int, NOT_NULL)
	(c0, blob, NULL)
	(c1, bool, NOT_NULL)
	(c2, float, NULL)
	(c3, tinyint, NULL)
	(c4, smallint, NOT_NULL)
	(c5, int, NULL)
	(c6, bigint, NOT_NULL)
	(c7, text, NULL)
	(c8, varchar(16), NOT_NULL)
	(c9, varchar(32), NULL)
)
```
this code will be generated:
https://gist.github.com/niXman/553de6d36f8176a1ce58

Ok for merge?
Any proposals/objections?

### CODE REVIEW

**Comment by niXman** [comment]
Now I'm open for discussion about code-generation for creation of tables.

**Comment by niXman** [comment]
I'll add the description about `ppgen` requirements: `boost.preprocessor-1.57 or greater is requered`

**Comment by niXman** [comment]
Ping?

**Comment by rbock** [comment]
It is still based on the old table structure, I am afraid. I changed that end of November. It should be fairly easy to adapt, but you need to update your fork.

Also, it would be great if you could add a test minimalistic test that does something with the generated table. Since the rest of the library works without boost, it might be a good idea to check if boost is available before compiling it.

**Comment by niXman** [comment]
> It is still based on the old table structure, I am afraid. I changed that end of November. It should be fairly easy to adapt, but you need to update your fork.

Ok...

> it would be great if you could add a test minimalistic test that does something with the generated table.

Ok.

> Since the rest of the library works without boost, it might be a good idea to check if boost is available before compiling it.

How do you suggest to do that?

**Comment by rbock** [comment]
Checking for boost: I haven't tried it yet, but this looks promising:

http://stackoverflow.com/a/6646746/2173029

**Pull request closed without merging**
