### PR TITLE
added msvc workaround & fixed minor bugs in tests

### PR DESCRIPTION
**Pull request by isliser**

### CODE REVIEW

**Comment by rbock** [comment]
Almost there, it seems (although clang/gcc is broken now)

For MSVC, for some reason, the linker is totally unhappy and there also is a problem in the assert tests.

**Comment by isliser** [comment]
I'm trying to find out what's wrong

**Comment by rbock** [comment]
Thanks! I'll be back in the evening.

**Comment by isliser** [comment]
I suppose that AppVeyor build fails because of build\examples\example_main.cpp file. In this file methods insert, remove, select & update are declared as int(int,char * * const) whereas they are defined as int(int, char**)

**Comment by rbock** [comment]
The build\tests\test_main.cpp is generated the same way by cmake. Any idea why it would work in tests, but not examples?

**Comment by isliser** [comment]
It fails on all projects. You can see it https://ci.appveyor.com/project/rbock/sqlpp11/build/1.0.12/job/sql561kr9dj7vaaa

**Comment by rbock** [comment]
Hmm, seems I did not wait long enough before searching for those errors. Will try to figure something out in the evening.

**Comment by isliser** [comment]
Fix no_conversion_operator_if_null_not_trivial please. I cannot comprehend the idea behind it :(

**Comment by rbock** [comment]
The idea is that when NULL is not interpreted as trivial and the value can be NULL, then the conversion `int i = row.alpha` is not valid.

I am not particularly fond of the tests in that folder myself. I will replace them sooner or later...

**Comment by rbock** [comment]
I'll merge this pull request, try to fix the example/tests folders and then see what I can do about the conversion_operator thingy...

**Comment by rbock** [comment]
Oh, wow, you fixed the tests already! Thanks!

**Comment by rbock** [comment]
Well, that'll teach me: The test did not even work correctly. I'll repair that (and think of a new test, shortly).

**Pull request merged**
