### PR TITLE
Ddl2cpp empty table check

### PR DESCRIPTION
**Pull request by digitalist**
could you please take a look at this patch

goal is:
- to remove hardcoded number of command line options 
- supprot -enable_feature -no-enable_feature
- some minor PEP related issues
- add error/warning instead of silent generation of "empty/useless" header
- add help message with options descriptions (only for optional args currently)

### CODE REVIEW

**Comment by digitalist** [comment]
examples:
ddl2cpp -no-timestamp-warning  db.sql db db #disable timestamp warning

ddl2cpp -no-timestamp-warning -no-warn-on-parse db.sql db db #no warn on parsing errors (enabled by default)

ddl2cpp -no-timestamp-warning -warn-on-parse db.sql db db #warn on parsing error, but continue 

ddl2cpp -no-timestamp-warning -fail-on-parse db.sql db db #exit on parsing failure

**Comment by digitalist** [comment]
@rbock  maybe I should remake this pr in dev-branch?

**Comment by rbock** [comment]
Sorry for the long silence on this one. Yes, a PR for develop would be great!

Also, if you have time for that, maybe you could add a few tests for ddl2cpp? For example, generate some header files and see if the tables/columns have the expected traits. It would make it easier to make sure that future changes do not break anything.

Cheers,

Roland

**Comment by digitalist** [comment]
moving pr to dev branch

**Pull request closed without merging**
