### PR TITLE
Further improvement on connection_pool.

### PR DESCRIPTION
**Pull request by fpark12**
This PR mainly tracks any refactoring and redesigning of connection_pool related code that emerge during the development of async query.

### CODE REVIEW

**Comment by fpark12** [comment]
Just moved `is_callable` to type_traits.h and renamed it to `is_invocable`. I also modified select.h to support `connection_pool` and `pool_connection` #162 @Erroneous1  @rbock

**Comment by fpark12** [comment]
It seems to be more complicated than I thought. I'll reverted the select.h commit and will look at it again when I have more time.

**Comment by csboling** [comment]
Awesome turnaround time on this! Looks like `query_task.h` that is now referenced by `connection_pool.h` did not get checked in?

**Comment by fpark12** [comment]
It is still WIP. The other PR is tracking th development of query_task.h. We need a bit more time before finalizing the design. As it currently stands the code is still kind of messy.

**Comment by fpark12** [comment]
This branch is merged into feature/async_query branch. Closing this PR as it is no longer needed.

**Comment by mickeyzoox** [comment]
@fpark12 Is this feature something that you'd expect others to be able to use?

I'm using dynamic queries and would like a query pool, but https://github.com/rbock/sqlpp11/issues/162 means it's not very clean (I actually haven't quite gotten it working).

**Comment by fpark12** [comment]
Hi @mickeyzoox

Thank you for your message. I am not physically well at the moment to participate in the development of this feature. This definitely needs some tweaking to work with your project, but the big features are all there. I don’t remember much about the code we wrote, but if you are willing to spend a little time you should be able to get it working. Sorry!

**Comment by mickeyzoox** [comment]
@fpark12 No worries, thanks for laying the groundwork!

**Pull request closed without merging**
