### PR TITLE
ppgen reformated

### PR DESCRIPTION
**Pull request by niXman**
subj

### CODE REVIEW

**Comment by niXman** [comment]
Ah yes - formated manually.
Please do not format `ppgen` sources automatically ;)

**Comment by rbock** [comment]
Yeah, that makes sense :-)
Can you add thee markers to prevent clang-format from acting on these files?

**Comment by niXman** [comment]
@rbock What should I do?

**Comment by rbock** [comment]
You insert at the top of the file

```
// clang-format off
```

See also:
http://clang.llvm.org/docs/ClangFormatStyleOptions.html#disabling-formatting-on-a-piece-of-code

**Comment by rbock** [comment]
Hi,

Are you going to insert those clang-format comments? Or should I do that?

Just asking to prevent a deadlock ;-)

Cheers,

Roland

**Comment by niXman** [comment]
Done!

Sorry for the delay.

**Comment by niXman** [comment]
ping?

**Comment by rbock** [comment]
Thanks! I saw the failed checks but that was an artifact.

**Pull request merged**
